INSERT INTO dish (name, price, description) VALUES
    ('Margherita Pizza', 12.99, 'Classic pizza with tomato sauce, mozzarella, and basil'),
    ('Pepperoni Pizza', 14.99, 'Pizza with tomato sauce, mozzarella, and pepperoni'),
    ('Caesar Salad', 8.99, 'Fresh romaine lettuce, croutons, parmesan cheese with Caesar dressing'),
    ('Greek Salad', 9.99, 'Mixed greens, feta cheese, olives, tomatoes, cucumber'),
    ('Cheeseburger', 11.99, 'Beef patty with cheddar cheese, lettuce, tomato, and onion'),
    ('Bacon Burger', 13.99, 'Beef patty with bacon, cheddar cheese, lettuce, tomato'),
    ('Spaghetti Carbonara', 15.99, 'Classic pasta with eggs, cheese, pancetta, and black pepper'),
    ('Fettuccine Alfredo', 14.99, 'Pasta in creamy parmesan sauce'),
    ('Grilled Salmon', 19.99, 'Fresh salmon fillet with herbs and lemon'),
    ('Chicken Alfredo', 16.99, 'Grilled chicken with fettuccine in alfredo sauce'),
    ('Vegetable Stir Fry', 12.99, 'Mixed vegetables in Asian sauce with rice'),
    ('Beef Stir Fry', 15.99, 'Sliced beef with vegetables in Asian sauce'),
    ('Fish and Chips', 13.99, 'Battered cod with french fries and tartar sauce'),
    ('Chicken Wings', 11.99, 'Crispy wings with choice of sauce'),
    ('Chicken Tenders', 10.99, 'Breaded chicken strips with dipping sauce'),
    ('BBQ Ribs', 21.99, 'Slow-cooked pork ribs with BBQ sauce'),
    ('Shrimp Scampi', 18.99, 'Garlic butter shrimp with pasta'),
    ('Mushroom Risotto', 14.99, 'Creamy rice with mushrooms and parmesan'),
    ('Beef Lasagna', 16.99, 'Layered pasta with meat sauce and cheese'),
    ('Vegetable Lasagna', 15.99, 'Layered pasta with vegetables and cheese'),
    ('Club Sandwich', 9.99, 'Triple-decker with turkey, bacon, lettuce, tomato'),
    ('BLT Sandwich', 8.99, 'Bacon, lettuce, and tomato sandwich'),
    ('French Onion Soup', 7.99, 'Classic onion soup with melted cheese'),
    ('Tomato Soup', 6.99, 'Creamy tomato soup with croutons'),
    ('French Fries', 4.99, 'Crispy potato fries with seasoning'),
    ('Onion Rings', 5.99, 'Battered and fried onion rings'),
    ('Mozzarella Sticks', 6.99, 'Breaded and fried cheese sticks'),
    ('Chicken Noodle Soup', 7.99, 'Classic chicken soup with vegetables'),
    ('Beef Tacos', 11.99, 'Three tacos with ground beef and toppings'),
    ('Fish Tacos', 12.99, 'Three tacos with grilled fish and slaw'),
    ('Chicken Quesadilla', 10.99, 'Grilled chicken and cheese in tortilla'),
    ('Beef Burrito', 11.99, 'Large burrito with beef, rice, and beans'),
    ('Veggie Burrito', 10.99, 'Large burrito with vegetables and rice'),
    ('Nachos Supreme', 13.99, 'Tortilla chips with all the toppings'),
    ('Chicken Curry', 15.99, 'Indian-style curry with rice'),
    ('Beef Curry', 16.99, 'Spicy beef curry with rice'),
    ('Pad Thai', 14.99, 'Thai noodles with chicken or shrimp'),
    ('Fried Rice', 11.99, 'Chinese-style rice with vegetables and egg'),
    ('Lo Mein', 12.99, 'Chinese noodles with vegetables'),
    ('Sweet and Sour Chicken', 13.99, 'Battered chicken in sweet and sour sauce'),
    ('Kung Pao Chicken', 13.99, 'Spicy chicken with peanuts and vegetables'),
    ('Beef and Broccoli', 14.99, 'Sliced beef with broccoli in brown sauce'),
    ('General Tsos Chicken', 13.99, 'Crispy chicken in sweet spicy sauce'),
    ('Orange Chicken', 13.99, 'Crispy chicken in orange sauce'),
    ('Chicken Teriyaki', 13.99, 'Grilled chicken with teriyaki sauce'),
    ('Beef Teriyaki', 14.99, 'Grilled beef with teriyaki sauce'),
    ('California Roll', 8.99, 'Sushi roll with crab and avocado'),
    ('Spicy Tuna Roll', 9.99, 'Sushi roll with spicy tuna'),
    ('Philadelphia Roll', 9.99, 'Sushi roll with salmon and cream cheese'),
    ('Dragon Roll', 12.99, 'Special sushi roll with eel and avocado'),
    ('Rainbow Roll', 13.99, 'California roll topped with assorted fish');